name: RestartMe
main: restartme.RestartMe
version: 1.0.0
api: 1.0.0
load: STARTUP
author: Gamecrafter
description: Make sure your server stays up all the time!
website: https://github.com/Viperize/RestartMe-Nukkit
permissions:
 restartme:
  default: op
  children:
   restartme.command:
    default: op
    children:
     restartme.command.restartme:
      default: op